const rootDir = process.env.WEFT_ROOT_DIR ?? process.cwd()
const shQuote = (value) => `'${value.replace(/'/g, "'\\''")}'`
const quotedFiles = (fileNames) => fileNames.map(shQuote).join(' ')

// pnpm owns the lockfile format. Prettier expands it, then the next `pnpm install` rewrites
// it compact again — a full-file diff each way.
const isPnpmLockfile = (fileName) => fileName === 'pnpm-lock.yaml' || fileName.endsWith('/pnpm-lock.yaml')

// docs/*.html are exported artifacts, 450 KB of generated markup. Reformatting them would be
// churn with a real chance of changing what they render.
const isExportedArtifact = (fileName) => /(^|\/)docs\/[^/]+\.html$/.test(fileName)

// build/ and results/ are generated by the compiler and the benchmark harness.
const isGenerated = (fileName) =>
  fileName.startsWith('build/') ||
  fileName.includes('/build/') ||
  fileName.startsWith('results/') ||
  fileName === 'CHANGELOG.md'

const withoutExcludedFiles = (fileNames) =>
  fileNames.filter(
    (fileName) => !isPnpmLockfile(fileName) && !isExportedArtifact(fileName) && !isGenerated(fileName),
  )

const buildCommand = (command, fileNames) => {
  const filtered = withoutExcludedFiles(fileNames)
  if (!filtered.length) return []
  return `${command} ${quotedFiles(filtered)}`
}

export default {
  '**/*.{js,mjs,cjs,ts,tsx,json,md,yaml,yml}': (fileNames) =>
    buildCommand(
      `prettier --config ${shQuote(`${rootDir}/prettier.config.js`)} --ignore-path ${shQuote(`${rootDir}/.prettierignore`)} --write --list-different`,
      fileNames,
    ),
  '**/*.{js,mjs,cjs,ts,tsx}': (fileNames) =>
    buildCommand(
      `oxlint --config ${shQuote(`${rootDir}/.oxlintrc.json`)} --fix --deny no-debugger`,
      fileNames,
    ),
}
