import { escapeHtml, heading, note, prose, table } from './markup.ts'
import { moduleById, surface, type ApiEntry, type ApiModule } from './surface.ts'

const KIND_ORDER: Record<string, number> = { function: 0, class: 1, interface: 2, type: 3, enum: 4, const: 5 }
const KIND_LABEL: Record<string, string> = {
  function: 'Functions',
  class: 'Classes',
  interface: 'Interfaces',
  type: 'Types',
  enum: 'Enums',
  const: 'Constants',
  unknown: 'Other',
}

const REPO = 'https://github.com/raminjafary/weft/blob/main'

function anchor(name: string): string {
  return name.replace(/[^A-Za-z0-9]+/g, '-').toLowerCase()
}

function entry(item: ApiEntry): string {
  return `<section class="api-entry" id="${anchor(item.name)}">
  <h3><a class="anchor" href="#${anchor(item.name)}"><code>${escapeHtml(item.name)}</code></a>
    <span class="kind">${escapeHtml(item.kind)}</span></h3>
  <figure class="code"><pre><code data-lang="ts">${escapeHtml(item.signature)}</code></pre></figure>
  ${
    item.doc
      ? `<div class="api-doc">${item.doc
          .split(/\n\s*\n/)
          .map((paragraph) => `<p>${inline(paragraph)}</p>`)
          .join('')}</div>`
      : `<p class="hint undocumented">No doc comment on the declaration. The signature and the file are all this page can honestly show.</p>`
  }
  <p class="hint"><a href="${REPO}/${escapeHtml(item.file)}"><code>${escapeHtml(item.file)}</code></a></p>
</section>`
}

/** Backticks become code, and nothing else is interpreted. A doc comment is prose, not markdown. */
function inline(text: string): string {
  return escapeHtml(text.replace(/\s+/g, ' ')).replace(/`([^`]+)`/g, '<code>$1</code>')
}

export function moduleList(currentId?: string): string {
  return `<h2 class="hint">Modules</h2><ul class="contents">${surface()
    .map(
      (module) =>
        `<li>${
          module.id === currentId
            ? `<strong>${escapeHtml(module.specifier)}</strong>`
            : `<a href="/api/${module.id}">${escapeHtml(module.specifier)}</a>`
        } <span class="count">${module.entries.length}</span></li>`,
    )
    .join('')}</ul>`
}

function coverage(module: ApiModule): { documented: number; total: number } {
  return {
    documented: module.entries.filter((item) => item.doc).length,
    total: module.entries.length,
  }
}

export function moduleBody(id: string): string {
  const module = moduleById(id)
  if (!module) {
    return `<div class="card"><h3>No such module</h3><p>Known: ${surface()
      .map((m) => `<a href="/api/${m.id}"><code>${escapeHtml(m.specifier)}</code></a>`)
      .join(', ')}</p></div>`
  }
  const { documented, total } = coverage(module)
  const groups = [...new Set(module.entries.map((e) => e.kind))].sort(
    (a, b) => (KIND_ORDER[a] ?? 9) - (KIND_ORDER[b] ?? 9),
  )

  return (
    prose(module.blurb) +
    `<p class="hint">Import as <code>${escapeHtml(module.specifier)}</code> · entry <code>${escapeHtml(
      module.entry,
    )}</code> · <strong>${total}</strong> exports, <strong>${documented}</strong> with a doc comment on the declaration.</p>` +
    groups
      .map(
        (kind) =>
          heading(KIND_LABEL[kind] ?? kind, `k-${kind}`) +
          module.entries
            .filter((item) => item.kind === kind)
            .map(entry)
            .join(''),
      )
      .join('')
  )
}

export function apiIndexBody(): string {
  const total = surface().reduce((sum, m) => sum + m.entries.length, 0)
  const documented = surface().reduce((sum, m) => sum + coverage(m).documented, 0)
  return (
    prose(
      `Every export of every package, read out of the source. <strong>${total}</strong> importable names ` +
        `across ${surface().length} entry points, of which <strong>${documented}</strong> carry a doc ` +
        'comment on the declaration itself.',
      '<code>weft</code> is much the largest because it is the front door: it re-exports the adapters, the ' +
        'kernel types and the plan types an application needs, so what you can import from it is what is ' +
        'listed under it. The same declaration therefore appears under both <code>weft</code> and the ' +
        'package it lives in, which is the truth about the import rather than a duplicate.',
      'The page is generated by walking each package’s public entry and following its re-exports, so adding ' +
        'an export adds a row and deleting one deletes a row. There is no second copy of the surface to ' +
        'keep in agreement with the first.',
    ) +
    note(
      'why',
      documented === total
        ? 'Both numbers are checked, and they are the same number'
        : `Why "${total} exports, ${documented} documented" is on the page rather than hidden`,
      documented === total
        ? 'Two tests hold this page: one walks the packages and fails if an export is missing here, and one ' +
            'fails if an export has no doc comment on its declaration. It was 384 of 1,367 when the page was ' +
            'first published — the ratio was printed rather than hidden, because a blank space a reader ' +
            'mistakes for a simple function is worse than an admission. Printing it is what made it worth ' +
            'closing.'
        : 'Coverage of the <em>surface</em> is complete and checked: a test walks the same tree and fails if ' +
            'any export is missing here. Coverage of the <em>prose</em> is not, and the honest thing is to ' +
            'publish the ratio and mark every entry that has none, rather than let a reader assume a blank ' +
            'space is a simple function.',
    ) +
    table(
      ['Module', 'Import as', 'Exports', 'With a doc comment'],
      surface().map((module) => {
        const { documented: n, total: t } = coverage(module)
        return [
          `<a href="/api/${module.id}">${escapeHtml(module.title)}</a>`,
          `<code>${escapeHtml(module.specifier)}</code>`,
          String(t),
          `${n} <span class="hint">(${Math.round((n / Math.max(1, t)) * 100)}%)</span>`,
        ]
      }),
    )
  )
}

export function moduleOutline(id: string): string {
  const module = moduleById(id)
  if (!module) return ''
  const { documented, total } = coverage(module)
  return `<h2 class="hint">This module</h2>
    <dl class="prov">
      <dt>Import</dt><dd><code>${escapeHtml(module.specifier)}</code></dd>
      <dt>Entry</dt><dd><code>${escapeHtml(module.entry)}</code></dd>
      <dt>Exports</dt><dd>${total}</dd>
      <dt>Documented</dt><dd>${documented}</dd>
    </dl>
    <h2 class="hint">On this page</h2>
    <ul class="contents outline">${module.entries
      .map((item) => `<li><a href="#${anchor(item.name)}"><code>${escapeHtml(item.name)}</code></a></li>`)
      .join('')}</ul>`
}

/** Every module id, for the route's declared params — which is what makes these pages files. */
export function moduleIds(): string[] {
  return surface().map((module) => module.id)
}
