import { escapeHtml, heading, note, prose, sketch, table } from './markup.ts'
import { diff, stats, terminal } from './figures.ts'

/**
 * One page, built from nothing, one step at a time.
 *
 * The tutorial's job is different from the guide's: the guide explains a mechanism, and this shows
 * what a mechanism costs by having you add it. Every step says what changed, what the framework then
 * knew, and what command shows it — because "run `weft why /` and look at the plan" is the habit
 * worth teaching, and no amount of prose replaces it.
 */
/**
 * The four parts, and what each one is for.
 *
 * A tutorial with no parts is a list, and a list of six is already long enough that a reader on
 * step four has no idea whether they are near the end. The parts are the answer to "where am I",
 * which is the question a step count on its own does not answer: `4 of 6` is a position and
 * `Change it` is a place.
 */
export interface Part {
  id: string
  /** `Part one`, spelled, because it is read as a name and not counted. */
  ordinal: string
  label: string
  blurb: string
}

export const PARTS: readonly Part[] = [
  {
    id: 'build',
    ordinal: 'Part one',
    label: 'Build it',
    blurb: 'A folder becomes an application, and the markup in it becomes sealed templates.',
  },
  {
    id: 'deliver',
    ordinal: 'Part two',
    label: 'Deliver it',
    blurb: 'The page reads something, and the slow half stops holding the fast half up.',
  },
  {
    id: 'change',
    ordinal: 'Part three',
    label: 'Change it',
    blurb: 'A write with an authority, and a region that shows the result without a reload.',
  },
  {
    id: 'ship',
    ordinal: 'Part four',
    label: 'Ship it',
    blurb: 'What the build says it produced, and the tier the deployment lands in.',
  },
]

export const PART_BY_ID: Record<string, Part> = Object.fromEntries(PARTS.map((part) => [part.id, part]))

export interface Step {
  slug: string
  title: string
  lede: string
  /** Which part of the tutorial this step is in. One of `PARTS`. */
  part: string
  /**
   * What this step is for, in one sentence, above the work.
   *
   * A tutorial step is a list of edits, and a reader part-way down one has usually lost the thread
   * of why they are making them. The goal sits between the lede and the first edit so that thread
   * is one glance away rather than a scroll back up.
   */
  goal: string
  body: () => string
}

export const STEPS: readonly Step[] = [
  {
    slug: 'a-page',
    part: 'build',
    title: '1 — A page',
    lede: 'One file is an application. Nothing is configured and nothing is generated by hand.',
    goal:
      'Get a page serving from a folder, and see that the route table, the plan and the tier were all ' +
      'derived from where the file sits rather than from anything you wrote down.',
    body: () =>
      prose(
        'Start with a folder. There is no template to instantiate, no config to write, and nothing to ' +
          'register — a route is a file, and this one is the only file you need.',
      ) +
      heading('1 · Make the folder', 'folder') +
      sketch(
        'sh',
        `mkdir shop && cd shop
npm init -y && npm i weft
mkdir -p app/routes`,
      ) +
      heading('2 · Write the one file', 'file') +
      sketch(
        'tsx',
        `// app/routes/index.tsx
import { fragment } from '@weftjs/core'

export default fragment(() => (
  <section>
    <h2>Today</h2>
    <p>Nothing yet.</p>
  </section>
))`,
      ) +
      heading('3 · Serve it', 'serve') +
      sketch('sh', 'npx weft dev') +
      heading('4 · Ask the framework what it knows', 'knows') +
      prose(
        'There is no <code>app/layout.tsx</code>, so the page is wrapped in the framework’s own document. ' +
          'Ask what the plan is:',
      ) +
      sketch('sh', 'npx weft routes\nnpx weft why /') +
      prose(
        'One route, one slot named <code>body</code>, delivery <code>buffered</code>. Nothing streams because ' +
          'nothing asked to, and nothing is keyed because the fragment reads nothing — which means this page ' +
          'is already in the tier where a document is a file. <code>npx weft build</code> writes it as one.',
      ),
  },
  {
    slug: 'the-document',
    part: 'build',
    title: '2 — The document',
    lede: 'Take over the shell, and discover that its holes are a contract.',
    goal:
      'Replace the framework’s document with your own, and find out that its slot holes are now a ' +
      'contract every route under it has to fill.',
    body: () =>
      prose(
        'The framework’s document is a placeholder. Replacing it is adding one file, and the moment you do, ' +
          'its <code>&lt;slot&gt;</code> holes become the boundaries every route has to fill.',
      ) +
      heading('1 · Take over the shell', 'shell') +
      sketch(
        'tsx',
        `// app/layout.tsx
import { fragment, raw } from '@weftjs/core'

interface Props {
  title: string
  css: string
  runtime: string
  body: string
  aside: string
}

export default fragment(({ title, css, runtime, body, aside }: Props) => (
  <>
    {raw('<!doctype html>')}
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>{title}</title>
        <link rel="stylesheet" href={css} />
        <script type="module" src={runtime} />
      </head>
      <body>
        <main><slot name="body">{body}</slot></main>
        <aside><slot name="aside">{aside}</slot></aside>
      </body>
    </html>
  </>
))`,
      ) +
      note(
        'careful',
        'The build now fails, and that is the feature',
        'Two holes and one route that fills one of them: <code>E_SHELL_HOLE_UNFILLED</code> names ' +
          '<code>aside</code>. A hole nothing fills would otherwise be an empty box in production that ' +
          'nobody noticed, so it is a build error instead.',
      ) +
      prose('Fill it from the route’s declaration:') +
      sketch(
        'ts',
        `// app/routes/index.data.ts
import { defineRoute } from '@weftjs/core'

export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      prose(
        'Note what is <em>not</em> here. <code>body</code> is not declared: the route’s own ' +
          '<code>.tsx</code> fills it, which is the one convention the hole names rely on. ' +
          '<code>title</code>, <code>css</code> and <code>runtime</code> are not declared either — the ' +
          'framework supplies six values every document may read, and a hole outside that set has to come ' +
          'from <code>layoutValues</code> or the build says so.',
      ),
  },
  {
    slug: 'a-loader',
    part: 'deliver',
    title: '3 — Data, and the first cache key',
    lede: 'Load something. Watch the cache class change without declaring one.',
    goal:
      'Read something per request and watch the cache key derive itself from that read — without ' +
      'writing a key, because there is nowhere to write one.',
    body: () =>
      prose(
        'A slot’s <code>load</code> is where data comes from. Its result is the value set the fragment ' +
          'renders with — there is no separate props step and no context to thread.',
      ) +
      sketch(
        'tsx',
        `// app/fragments/today.tsx
import { fragment } from '@weftjs/core'

interface Item { sku: string; name: string; price: number }

export default fragment(({ items }: { items: Item[] }) => (
  <ul>
    {items.map((item) => (
      <li><code>{item.sku}</code> {item.name} — {item.price}</li>
    ))}
  </ul>
))`,
      ) +
      sketch(
        'ts',
        `// app/routes/index.data.ts
export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    body: { fragment: 'today', load: async () => ({ items: await db.today() }) },
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      heading('2 · Now make it vary', 'vary') +
      prose(
        'Read the request inside the fragment and the page changes class. One line, and nothing declares ' +
          'the consequence:',
      ) +
      sketch(
        'tsx',
        `export default fragment(({ items }: { items: Item[] }, ctx) => {
  const currency = ctx.cookie('currency') ?? 'USD'
  return <ul data-currency={currency}>…</ul>
})`,
      ) +
      table(
        ['Before', 'After'],
        [
          [
            'reads nothing → <code>static</code>, resolvable at build time',
            'reads <code>cookie:currency</code> → <code>shared</code>, keyed by value, <code>Vary: Cookie</code>',
          ],
        ],
      ) +
      prose(
        '<code>npx weft build</code> now refuses to write this page as a file, and says which read stopped ' +
          'it. That refusal is the whole design in one line: the cheapest tier is not something you opt ' +
          'into, it is something a read takes you out of.',
      ),
  },
  {
    slug: 'a-slow-region',
    part: 'deliver',
    title: '4 — A slow region, and the first byte',
    lede: 'Add something slow and watch the shell stop waiting for it.',
    goal:
      'Take the feed out of the critical path without moving it out of the document, and read the two ' +
      'numbers that prove it: time to first byte, and when the fast half became visible.',
    body: () =>
      prose(
        'One region on the page is slow — a recommendation query, say. Declare that it streams, and the ' +
          'document stops being downstream of it.',
      ) +
      heading('1 · Declare the hole', 'declare') +
      diff(
        [
          "  feed: { fragment: 'feed' },",
          "+ feed: { fragment: 'feed', stream: true,",
          "+         placeholder: 'feed/skeleton' },",
        ],
        'app/routes/index.data.ts',
      ) +
      prose(
        'The plan’s delivery order was <code>in-order</code> and is now <code>out-of-order</code>, because ' +
          'a slot asked to stream. That is derived, not declared: a page whose regions are uniformly fast ' +
          'never puts the fill script on the wire at all.',
      ) +
      heading('2 · Read what it cost', 'cost') +
      stats([
        { value: '43.5 ms', note: 'TTFB, unchanged — the shell never read the feed', lit: true },
        { value: '22 ms', note: 'fast region visible, from 103 ms', lit: true },
        { value: '+329 B', note: 'inline script, the whole price of out-of-order' },
      ]) +
      heading('3 · Ask the framework why', 'why-it') +
      terminal('why-slow', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  shell    app/layout.tsx → routes/index.tsx',
            '  wave 1   header (buffered) · feed (stream)',
            '  wave 2   prices needs feed',
            '  keys     header: static · feed: shared route:page · prices: shared',
          ],
        },
      ]) +
      heading('What a placeholder is for', 'placeholder') +
      prose(
        'It is what arrives if the region degrades — over budget, or a loader that threw. Honest, cheap and ' +
          'visibly incomplete, which is the only useful behaviour: a region that failed and rendered ' +
          'something plausible is worse than one that failed and said so.',
      ) +
      note(
        'why',
        'Why the first byte does not move',
        'The shell’s bytes do not depend on the slow loader — that is what makes it a hole rather than part ' +
          'of the document. So the header, the nav and everything before the slot are on the wire while the ' +
          'query is still running, and the reader sees a page rather than a spinner.',
      ),
  },
  {
    slug: 'making-it-change',
    part: 'change',
    title: '5 — Making it change',
    lede: 'An intent to write, and a live region to show the result.',
    goal:
      'Write something — the one way this framework allows it — and have the regions that went stale ' +
      'refresh themselves because the intent declared which ones they were.',
    body: () =>
      prose(
        'A render cannot write. So a mutation is an intent, in its own directory, declaring the tags it may ' +
          'invalidate:',
      ) +
      heading('1 · Declare the intent', 'declare-intent') +
      sketch(
        'ts',
        `// app/intents/cart.ts
import { defineIntent } from '@weftjs/core'

export const add = defineIntent<{ sku: string }>({
  name: 'cart.add',
  writes: ['cart'],
  input: (raw) => ({ sku: String((raw as { sku?: unknown }).sku ?? '') }),
  async run(ctx, { sku }) {
    await db.cart.add(ctx.session, sku)
    await ctx.revalidate('cart')
  },
})`,
      ) +
      heading('2 · Name it from a control', 'name-it') +
      prose('Wire it to a control by naming it, not by writing a handler:') +
      sketch(
        'tsx',
        `import { add } from '../intents/cart.ts'

<button onClick={add} data-sku={item.sku}>add</button>`,
      ) +
      prose(
        'With no JavaScript this is a form post, dispatched in phase A, so a real status and a 303 are both ' +
          'available. With the runtime present it goes over the channel, the client stages its guess in an ' +
          'epoch, and the server replaces the guess with the truth in one paint.',
      ) +
      heading('3 · Make the region live', 'live') +
      sketch('ts', `body: { fragment: 'cart', live: true, load: loadCart }`) +
      prose(
        '<code>live</code> is what lets a region be refreshed over the channel rather than by reloading the ' +
          'page. What arrives is the smallest form the client can prove it can apply — usually a delta, which ' +
          'is the changed values and nothing else.',
      ),
  },
  {
    slug: 'shipping-it',
    part: 'ship',
    title: '6 — Shipping it',
    lede: 'Build, look at what the build says, and deploy the tier below the kernel.',
    goal:
      'Build the application, read which pages became files and why the rest did not, and serve the ' +
      'result from the tier where the kernel is never invoked.',
    body: () =>
      prose('The build is one command, and its report is the thing worth reading:') +
      heading('1 · Build it', 'build') +
      sketch('sh', 'npx weft build') +
      prose(
        'It prints a line per route — slots, markup bytes, stylesheets — then the L0 section: which pages ' +
          'were resolved at build time and written as files, and for every page that was not, the code and ' +
          'the read that refused it. That list is the performance review of your application, and it is ' +
          'generated rather than requested.',
      ) +
      heading('2 · Serve it, and check it', 'serve-it') +
      sketch(
        'sh',
        `npx weft start          # serve the build. No compiler runs
npx weft verify --probe # ask every region what it is serving
npx weft upload --to …  # PUT the build to an object store`,
      ) +
      heading('3 · What to do next', 'next') +
      prose(
        'Two things pay for themselves immediately. <code>weft dev --profile</code> records what every ' +
          'render costs and lets the next build plan delivery from measurement instead of a guess — ' +
          '<a href="/guide/measuring">a plan generated from measurement</a>. And <code>pnpm inspect</code> ' +
          'opens the inspector — a page per mechanism, each with a control — which is the fastest way to ' +
          'build an intuition for what any of this costs.',
      ) +
      prose('Then, in the guide, the four pages this tutorial deliberately did not stop for:') +
      table(
        ['Page', 'What it adds to what you just built'],
        [
          [
            '<a href="/guide/navigation">Instant navigation</a>',
            'A click that commits a route already fetched, parsed and painting nothing.',
          ],
          [
            '<a href="/guide/where-it-runs">Where it runs</a>',
            'Executors as crash domains, and why a CPU budget is advisory on one of them.',
          ],
          [
            '<a href="/guide/composition">Composition</a>',
            'A region that renders on another deployment, over the protocol you already have.',
          ],
          [
            '<a href="/guide/what-ships">What the page downloads</a>',
            'The ceiling per client entry, and the honest number that is bigger than all of them.',
          ],
        ],
      ),
  },
]

export const STEP_BY_SLUG: Record<string, Step> = Object.fromEntries(STEPS.map((step) => [step.slug, step]))

/**
 * `Part two · Step 4 of 6`, counted rather than written.
 *
 * The step's own title already carries its number, which is exactly why this is derived: two places
 * saying the same number is one place that can be wrong after a step is inserted. The part is in
 * front of it because a position needs somewhere to be a position in — `4 of 6` says how far and
 * the part says where.
 */
export function stepKicker(slug: string): string {
  const at = STEPS.findIndex((step) => step.slug === slug)
  if (at < 0) return ''
  const part = PART_BY_ID[STEPS[at]?.part ?? '']
  return `${part ? `${part.ordinal} · ` : ''}Step ${at + 1} of ${STEPS.length}`
}

/**
 * What a step actually has you run, and what it has you hit.
 *
 * Read out of the step's own markup rather than listed beside it: a step that gains a command gains
 * a line here, and a step whose command is renamed cannot go on advertising the old one. The codes
 * are the same bargain — a step that shows a refusal is a step whose card should say which one,
 * because that is what somebody scanning for the answer to an error is scanning for.
 */
export function stepMentions(slug: string): string[] {
  const step = STEP_BY_SLUG[slug]
  if (!step) return []
  const markup = step.body()
  const text = markup.replace(/<[^>]+>/g, ' ')
  const commands = [...text.matchAll(/\bweft ([a-z]+)(?: (\/[a-z-]*))?/g)].map(
    (match) => `weft ${match[1]}${match[2] ? ` ${match[2]}` : ''}`,
  )
  const codes = [...text.matchAll(/\bE_[A-Z0-9_]+/g)].map((match) => match[0])
  return [...new Set([...commands, ...codes])].slice(0, 3)
}

/**
 * How long a step takes, in whole minutes, from the step itself.
 *
 * The design puts a time under each step's progress count, and a time somebody typed is a time that
 * is wrong the first time the step grows. So it is counted from the step.
 *
 * Not reading time — this is a tutorial, and the reader is typing and running things. Prose at 200
 * words a minute, plus three minutes for every block they have to type and watch the result of,
 * which is where a tutorial step's time actually goes. On the step the design costed, that comes
 * out at the eight minutes the design says.
 */
const READING = 200
const PER_BLOCK = 3

export function stepMinutes(slug: string): number {
  const step = STEP_BY_SLUG[slug]
  if (!step) return 0
  const markup = step.body()
  const words = markup
    .replace(/<[^>]+>/g, ' ')
    .split(/\s+/)
    .filter(Boolean).length
  const blocks = (markup.match(/<pre/g) ?? []).length
  return Math.max(2, Math.ceil(words / READING + blocks * PER_BLOCK))
}

/** `about eight minutes`, because a numeral there reads as a promise and a word reads as an estimate. */
const SPELLED = [
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
]

export function stepTime(slug: string): string {
  const minutes = stepMinutes(slug)
  return `about ${SPELLED[minutes] ?? minutes} minutes`
}

/**
 * What the reader's application looks like at the end of each step.
 *
 * The design puts this in the rail, and it earns its place: a tutorial adds a file at a time and by
 * step four the reader has six of them, with no single view of what they now have. The files a step
 * *touched* are marked, so the rail also answers "what did I just change".
 *
 * Cumulative by construction — each step names only what it adds, and the tree is the union of
 * every step up to and including this one. A step cannot forget to list a file it added earlier.
 */
const ADDS: Record<string, readonly string[]> = {
  'a-page': ['app/', 'app/routes/', 'app/routes/index.tsx'],
  'the-document': ['app/layout.tsx'],
  'a-loader': ['app/routes/index.data.ts'],
  'a-slow-region': [
    'app/fragments/',
    'app/fragments/feed.tsx',
    'app/fragments/feed/',
    'app/fragments/feed/skeleton.tsx',
  ],
  'making-it-change': ['app/intents/', 'app/intents/cart.ts'],
  'shipping-it': ['weft.config.ts'],
}

export interface TreeRow {
  path: string
  depth: number
  name: string
  /** Added by the step being read, rather than by one before it. */
  fresh: boolean
}

export function appSoFar(slug: string): TreeRow[] {
  const upTo = STEPS.findIndex((step) => step.slug === slug)
  if (upTo < 0) return []
  const seen: string[] = []
  for (const step of STEPS.slice(0, upTo + 1)) {
    for (const path of ADDS[step.slug] ?? []) if (!seen.includes(path)) seen.push(path)
  }
  const fresh = new Set(ADDS[slug] ?? [])
  return seen.toSorted().map((path) => {
    const parts = path.replace(/\/$/, '').split('/')
    return {
      path,
      depth: parts.length - 1,
      name: path.endsWith('/') ? `${parts.at(-1)}/` : (parts.at(-1) ?? path),
      fresh: fresh.has(path),
    }
  })
}

/**
 * The tutorial's front page: what it costs, then the parts, then the steps in each.
 *
 * Every number on it is counted from the steps — the count, the minutes, the files the reader ends
 * with — because a tutorial index is exactly the page where an estimate somebody typed goes stale
 * first. A part is a row: what it is for on the left, and the steps in it on the right, so the
 * shape of the whole tutorial is one screen rather than a list of six titles.
 */
export function tutorialIndexBody(): string {
  const minutes = STEPS.reduce((sum, step) => sum + stepMinutes(step.slug), 0)
  const last = STEPS.at(-1)
  const files = last ? appSoFar(last.slug).filter((row) => !row.path.endsWith('/')).length : 0

  return (
    stats([
      { value: String(STEPS.length), note: `steps, in ${PARTS.length} parts` },
      { value: clock(minutes), note: 'end to end, counted from the steps themselves' },
      { value: String(files), note: 'files in the application by the last step' },
      { value: '1', note: 'application, carried the whole way', lit: true },
    ]) +
    `<p class="hint tutorial-needs">You need Node 22 or later and nothing else. There is no scaffolding
     step you cannot read, and every step says what changed, what the framework then knew, and which
     command shows it.</p>` +
    PARTS.map((part) => {
      const steps = STEPS.filter((step) => step.part === part.id)
      if (!steps.length) return ''
      const takes = steps.reduce((sum, step) => sum + stepMinutes(step.slug), 0)
      return `<section class="part" id="${escapeHtml(part.id)}">
        <div class="part-of">
          <p class="eyebrow">${escapeHtml(part.ordinal)}</p>
          <h2><a class="anchor" href="#${escapeHtml(part.id)}">${escapeHtml(part.label)}</a></h2>
          <p>${escapeHtml(part.blurb)}</p>
          <p class="hint">${clock(takes)}</p>
        </div>
        <div class="part-steps">${steps.map(stepCard).join('')}</div>
      </section>`
    }).join('')
  )
}

/** One step, as the index shows it: where it is, what it does, and what it has you run. */
function stepCard(step: Step): string {
  const at = STEPS.findIndex((other) => other.slug === step.slug) + 1
  const mentions = stepMentions(step.slug)
  return `<a class="step-card" href="/tutorial/${escapeHtml(step.slug)}">
    <div class="step-card-head">
      <span class="step-num">${String(at).padStart(2, '0')}</span>
      <span class="step-title">${escapeHtml(step.title.replace(/^\d+\s*—\s*/, ''))}</span>
      <span class="step-mins">${stepMinutes(step.slug)} min</span>
    </div>
    <p>${escapeHtml(step.lede)}</p>
    ${mentions.length ? `<p class="step-runs">${mentions.map(escapeHtml).join(' · ')}</p>` : ''}
  </a>`
}

/** `2 h 43` where it runs past an hour, and `43 min` where it does not. */
function clock(minutes: number): string {
  if (minutes < 60) return `${minutes} min`
  return `${Math.floor(minutes / 60)} h ${String(minutes % 60).padStart(2, '0')}`
}

export function stepBody(slug: string): string {
  const step = STEP_BY_SLUG[slug]
  if (!step)
    return `<div class="card"><h3>No such step</h3><p><a href="/tutorial">Start at the beginning</a>.</p></div>`
  const index = STEPS.findIndex((s) => s.slug === slug)
  const previous = index > 0 ? STEPS[index - 1] : undefined
  const next = index < STEPS.length - 1 ? STEPS[index + 1] : undefined
  return (
    `<div class="goal"><p class="goal-kicker">Goal</p><p>${escapeHtml(step.goal)}</p></div>` +
    step.body() +
    `<nav class="sequence">${[
      previous ? `<a class="prev" href="/tutorial/${previous.slug}">← ${escapeHtml(previous.title)}</a>` : '',
      next ? `<a class="next" href="/tutorial/${next.slug}">${escapeHtml(next.title)} →</a>` : '',
    ]
      .filter(Boolean)
      .join('')}</nav>`
  )
}
