import { escapeHtml, heading, note, prose, sketch, table } from './markup.ts'
import { diff, stats, terminal } from './figures.ts'

/**
 * One page, built from nothing, one step at a time.
 *
 * The tutorial's job is different from the guide's: the guide explains a mechanism, and this shows
 * what a mechanism costs by having you add it. Every step says what changed, what the framework then
 * knew, and what command shows it — because "run `weft why /` and look at the plan" is the habit
 * worth teaching, and no amount of prose replaces it.
 */
/**
 * The four parts, and what each one is for.
 *
 * A tutorial with no parts is a list, and a list of six is already long enough that a reader on
 * step four has no idea whether they are near the end. The parts are the answer to "where am I",
 * which is the question a step count on its own does not answer: `4 of 6` is a position and
 * `Change it` is a place.
 */
export interface Part {
  id: string
  /** `Part one`, spelled, because it is read as a name and not counted. */
  ordinal: string
  label: string
  blurb: string
}

export const PARTS: readonly Part[] = [
  {
    id: 'build',
    ordinal: 'Part one',
    label: 'Build it',
    blurb: 'A folder becomes an application, and the markup in it becomes sealed templates.',
  },
  {
    id: 'deliver',
    ordinal: 'Part two',
    label: 'Deliver it',
    blurb: 'The page reads something, and the slow half stops holding the fast half up.',
  },
  {
    id: 'change',
    ordinal: 'Part three',
    label: 'Change it',
    blurb: 'A write with an authority, and a region that shows the result without a reload.',
  },
  {
    id: 'ship',
    ordinal: 'Part four',
    label: 'Ship it',
    blurb: 'What the build says it produced, and the tier the deployment lands in.',
  },
]

export const PART_BY_ID: Record<string, Part> = Object.fromEntries(PARTS.map((part) => [part.id, part]))

export interface Step {
  slug: string
  title: string
  lede: string
  /** Which part of the tutorial this step is in. One of `PARTS`. */
  part: string
  /**
   * What this step is for, in one sentence, above the work.
   *
   * A tutorial step is a list of edits, and a reader part-way down one has usually lost the thread
   * of why they are making them. The goal sits between the lede and the first edit so that thread
   * is one glance away rather than a scroll back up.
   */
  goal: string
  body: () => string
}

export const STEPS: readonly Step[] = [
  {
    slug: 'a-page',
    part: 'build',
    title: 'A page',
    lede: 'One file is an application. Nothing is configured and nothing is generated by hand.',
    goal:
      'Get a page serving from a folder, and see that the route table, the plan and the tier were all ' +
      'derived from where the file sits rather than from anything you wrote down.',
    body: () =>
      prose(
        'Start with a folder. There is no template to instantiate, no config to write, and nothing to ' +
          'register — a route is a file, and this one is the only file you need.',
      ) +
      heading('1 · Make the folder', 'folder') +
      sketch(
        'sh',
        `mkdir shop && cd shop
npm init -y && npm i weft
mkdir -p app/routes`,
      ) +
      heading('2 · Write the one file', 'file') +
      sketch(
        'tsx',
        `// app/routes/index.tsx
import { fragment } from '@weftjs/core'

export default fragment(() => (
  <section>
    <h2>Today</h2>
    <p>Nothing yet.</p>
  </section>
))`,
      ) +
      heading('3 · Serve it', 'serve') +
      sketch('sh', 'npx weft dev') +
      heading('4 · Ask the framework what it knows', 'knows') +
      prose(
        'There is no <code>app/layout.tsx</code>, so the page is wrapped in the framework’s own document. ' +
          'Ask what the plan is:',
      ) +
      sketch('sh', 'npx weft routes\nnpx weft why /') +
      prose(
        'One route, one slot named <code>body</code>, delivery <code>buffered</code>. Nothing streams because ' +
          'nothing asked to, and nothing is keyed because the fragment reads nothing — which means this page ' +
          'is already in the tier where a document is a file. <code>npx weft build</code> writes it as one.',
      ),
  },
  {
    slug: 'the-document',
    part: 'build',
    title: 'The document, and documents that nest',
    lede: 'Take over the shell, and discover that its holes are a contract.',
    goal:
      'Replace the framework’s document with your own, and find out that its slot holes are now a ' +
      'contract every route under it has to fill.',
    body: () =>
      prose(
        'The framework’s document is a placeholder. Replacing it is adding one file, and the moment you do, ' +
          'its <code>&lt;slot&gt;</code> holes become the boundaries every route has to fill.',
      ) +
      heading('1 · Take over the shell', 'shell') +
      sketch(
        'tsx',
        `// app/layout.tsx
import { fragment, raw } from '@weftjs/core'

interface Props {
  title: string
  css: string
  runtime: string
  body: string
  aside: string
}

export default fragment(({ title, css, runtime, body, aside }: Props) => (
  <>
    {raw('<!doctype html>')}
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>{title}</title>
        <link rel="stylesheet" href={css} />
        <script type="module" src={runtime} />
      </head>
      <body>
        <main><slot name="body">{body}</slot></main>
        <aside><slot name="aside">{aside}</slot></aside>
      </body>
    </html>
  </>
))`,
      ) +
      note(
        'careful',
        'The build now fails, and that is the feature',
        'Two holes and one route that fills one of them: <code>E_SHELL_HOLE_UNFILLED</code> names ' +
          '<code>aside</code>. A hole nothing fills would otherwise be an empty box in production that ' +
          'nobody noticed, so it is a build error instead.',
      ) +
      prose('Fill it from the route’s declaration:') +
      sketch(
        'ts',
        `// app/routes/index.data.ts
import { defineRoute } from '@weftjs/core'

export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      prose(
        'Note what is <em>not</em> here. <code>body</code> is not declared: the route’s own ' +
          '<code>.tsx</code> fills it, which is the one convention the hole names rely on. ' +
          '<code>title</code>, <code>css</code> and <code>runtime</code> are not declared either — the ' +
          'framework supplies six values every document may read, and a hole outside that set has to come ' +
          'from <code>layoutValues</code> or the build says so.',
      ),
  },
  {
    slug: 'fragments-and-lists',
    part: 'build',
    title: 'Fragments, components and lists',
    lede: 'A sealed template with pre-encoded bytes, a component resolved at build time, and one row template projected per item.',
    goal:
      'Break the page into fragments, put one inside another, and render a list — then read the ' +
      'template the compiler sealed and find the holes it did not have to escape.',
    body: () =>
      prose(
        'The page is one fragment so far. A fragment is not a component that runs: it is a template the ' +
          'compiler sealed, with pre-encoded bytes between its holes and a version that is a hash of its ' +
          'content. Splitting the page up is therefore free at render time — what it costs is measured ' +
          'once, at build.',
      ) +
      heading('1 · One fragment inside another', 'inside') +
      prose(
        'A tag whose name is a fragment is resolved when the parent is compiled. There is no call site at ' +
          'runtime, no element to mount and nothing to reconcile — the child’s bytes are spliced into the ' +
          'parent’s, and its holes become the parent’s holes:',
      ) +
      sketch(
        'tsx',
        `// app/fragments/price.tsx
import { fragment } from '@weftjs/core'

export default fragment(({ amount }: { amount: number }) => (
  <b class="price">{amount}</b>
))`,
      ) +
      sketch(
        'tsx',
        `// app/fragments/item.tsx
import { fragment } from '@weftjs/core'
import Price from './price.tsx'

interface Item { sku: string; name: string; price: number }

export default fragment(({ item }: { item: Item }) => (
  <li>
    <code>{item.sku}</code> {item.name} — <Price amount={item.price} />
  </li>
))`,
      ) +
      heading('2 · A list is one row template, projected', 'rows') +
      prose(
        'A <code>map</code> in a template does not build markup per item. It compiles to a single row ' +
          'template that the renderer projects once per value, which is why a thousand rows cost one ' +
          'template rather than a thousand:',
      ) +
      sketch(
        'tsx',
        `export default fragment(({ items }: { items: Item[] }) => (
  <ul>{items.map((item) => <Item item={item} />)}</ul>
))`,
      ) +
      note(
        'refused',
        'A row has to be one element',
        'Return two siblings from a <code>map</code> and the build stops with ' +
          '<code>E_ROW_NOT_SINGLE_ROOT</code>. The reason is the projection: the renderer divides the ' +
          'parent’s children into rows, and it cannot do that if a row is a variable number of them.',
      ) +
      heading('3 · Look at what it sealed', 'sealed') +
      terminal('why-fragments', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  templates  4 sealed · 1 row template projected per item',
            '  holes      sku (text, escape) · name (text, escape) · amount (text, none)',
            '  reads      nothing — static',
          ],
        },
      ]) +
      prose(
        '<code>amount</code> is typed <code>number</code>, so the compiler knows it cannot hold markup and ' +
          'marks it as needing no escaping. You wrote that type for yourself; the template got the ' +
          'escape elision for free. See <a href="/guide/fragments">fragments and templates</a> for what a ' +
          'sealed template is, and <a href="/guide/components">one fragment inside another</a> for why ' +
          'composition has no runtime cost.',
      ),
  },
  {
    slug: 'scoped-styles',
    part: 'build',
    title: 'A component’s own stylesheet',
    lede: 'Name a sheet .scoped.css and its selectors reach only the elements that component declares.',
    goal:
      'Give the item component a stylesheet of its own, and see that the page links it only because ' +
      'that component rendered — and that its selectors cannot reach anything else.',
    body: () =>
      prose(
        'A stylesheet beside a fragment, named for it, belongs to it. There is no build step to configure ' +
          'and no class-name mangling to read in a devtools pane: the compiler knows which elements that ' +
          'template declares, so it can scope the selectors to exactly those.',
      ) +
      heading('1 · Write the sheet', 'sheet') +
      sketch(
        'css',
        `/* app/fragments/item.scoped.css */
li {
  display: flex;
  gap: 8px;
  padding: 6px 0;
}

.price {
  margin-inline-start: auto;
  font-variant-numeric: tabular-nums;
}`,
      ) +
      prose(
        'Bare <code>li</code>, and it is safe: the selector is rewritten to reach the <code>li</code> this ' +
          'template declares and nothing else. A sibling fragment with its own <code>li</code> is ' +
          'untouched, and so is one this component happens to contain.',
      ) +
      heading('2 · Check what the page linked', 'linked') +
      terminal('why-styles', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  css   layout.css · styles.css · fragments/item.scoped.css',
            '  note  item.scoped.css is linked because fragments/item rendered',
          ],
        },
      ]) +
      prose(
        'A page links the stylesheets of the components on it, and not the application’s whole design ' +
          'system. Remove the component and the link goes with it, because the link was never a line ' +
          'anybody wrote — see <a href="/guide/scoped-styles">a component’s own stylesheet</a>.',
      ),
  },
  {
    slug: 'a-loader',
    part: 'deliver',
    title: 'Data, and the first cache key',
    lede: 'Load something. Watch the cache class change without declaring one.',
    goal:
      'Read something per request and watch the cache key derive itself from that read — without ' +
      'writing a key, because there is nowhere to write one.',
    body: () =>
      prose(
        'A slot’s <code>load</code> is where data comes from. Its result is the value set the fragment ' +
          'renders with — there is no separate props step and no context to thread.',
      ) +
      sketch(
        'tsx',
        `// app/fragments/today.tsx
import { fragment } from '@weftjs/core'

interface Item { sku: string; name: string; price: number }

export default fragment(({ items }: { items: Item[] }) => (
  <ul>
    {items.map((item) => (
      <li><code>{item.sku}</code> {item.name} — {item.price}</li>
    ))}
  </ul>
))`,
      ) +
      sketch(
        'ts',
        `// app/routes/index.data.ts
export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    body: { fragment: 'today', load: async () => ({ items: await db.today() }) },
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      heading('2 · Now make it vary', 'vary') +
      prose(
        'Read the request inside the fragment and the page changes class. One line, and nothing declares ' +
          'the consequence:',
      ) +
      sketch(
        'tsx',
        `export default fragment(({ items }: { items: Item[] }, ctx) => {
  const currency = ctx.cookie('currency') ?? 'USD'
  return <ul data-currency={currency}>…</ul>
})`,
      ) +
      table(
        ['Before', 'After'],
        [
          [
            'reads nothing → <code>static</code>, resolvable at build time',
            'reads <code>cookie:currency</code> → <code>shared</code>, keyed by value, <code>Vary: Cookie</code>',
          ],
        ],
      ) +
      prose(
        '<code>npx weft build</code> now refuses to write this page as a file, and says which read stopped ' +
          'it. That refusal is the whole design in one line: the cheapest tier is not something you opt ' +
          'into, it is something a read takes you out of.',
      ),
  },
  {
    slug: 'a-slow-region',
    part: 'deliver',
    title: 'A slow region, and the first byte',
    lede: 'Add something slow and watch the shell stop waiting for it.',
    goal:
      'Take the feed out of the critical path without moving it out of the document, and read the two ' +
      'numbers that prove it: time to first byte, and when the fast half became visible.',
    body: () =>
      prose(
        'One region on the page is slow — a recommendation query, say. Declare that it streams, and the ' +
          'document stops being downstream of it.',
      ) +
      heading('1 · Declare the hole', 'declare') +
      diff(
        [
          "  feed: { fragment: 'feed' },",
          "+ feed: { fragment: 'feed', stream: true,",
          "+         placeholder: 'feed/skeleton' },",
        ],
        'app/routes/index.data.ts',
      ) +
      prose(
        'The plan’s delivery order was <code>in-order</code> and is now <code>out-of-order</code>, because ' +
          'a slot asked to stream. That is derived, not declared: a page whose regions are uniformly fast ' +
          'never puts the fill script on the wire at all.',
      ) +
      heading('2 · Read what it cost', 'cost') +
      stats([
        { value: '43.5 ms', note: 'TTFB, unchanged — the shell never read the feed', lit: true },
        { value: '22 ms', note: 'fast region visible, from 103 ms', lit: true },
        { value: '+329 B', note: 'inline script, the whole price of out-of-order' },
      ]) +
      heading('3 · Ask the framework why', 'why-it') +
      terminal('why-slow', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  shell    app/layout.tsx → routes/index.tsx',
            '  wave 1   header (buffered) · feed (stream)',
            '  wave 2   prices needs feed',
            '  keys     header: static · feed: shared route:page · prices: shared',
          ],
        },
      ]) +
      heading('What a placeholder is for', 'placeholder') +
      prose(
        'It is what arrives if the region degrades — over budget, or a loader that threw. Honest, cheap and ' +
          'visibly incomplete, which is the only useful behaviour: a region that failed and rendered ' +
          'something plausible is worse than one that failed and said so.',
      ) +
      note(
        'why',
        'Why the first byte does not move',
        'The shell’s bytes do not depend on the slow loader — that is what makes it a hole rather than part ' +
          'of the document. So the header, the nav and everything before the slot are on the wire while the ' +
          'query is still running, and the reader sees a page rather than a spinner.',
      ),
  },
  {
    slug: 'where-the-render-runs',
    part: 'deliver',
    title: 'Where the render runs',
    lede: 'A render is a DAG rather than a tree walk, executors are crash domains, and a budget is a limit where something can be preempted.',
    goal:
      'Put the slow region on an executor of its own, give it a budget, and watch the page degrade to ' +
      'the placeholder instead of failing — because the two regions were never on the same fate.',
    body: () =>
      prose(
        'The feed streams now, but it still runs where everything else runs. A render here is a graph and ' +
          'not a tree walk, so a region can be placed somewhere with a limit of its own — and a region ' +
          'that exceeds it is preempted rather than allowed to take the document with it.',
      ) +
      heading('1 · Give the feed its own executor', 'executor') +
      diff(
        [
          "  feed: { fragment: 'feed', stream: true,",
          "          placeholder: 'feed/skeleton',",
          "+         run: 'isolate', budget: { cpu: '40ms' } },",
        ],
        'app/routes/index.data.ts',
      ) +
      prose(
        'An executor is a crash domain. The feed throwing is now a region that degraded, and the ' +
          'placeholder is what arrives in its hole; before this it was a document that failed.',
      ) +
      heading('2 · Make it go over, on purpose', 'over') +
      sketch(
        'sh',
        `npx weft dev --slow feed=200ms   # spend more than the budget allows
npx weft why /`,
      ) +
      terminal('why-executor', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  feed     run: isolate · budget: cpu 40ms · degraded → feed/skeleton',
            '  document settled 43.5 ms — the shell never waited',
          ],
        },
      ]) +
      note(
        'careful',
        'A CPU budget is advisory on some executors',
        'Where the runtime cannot preempt — an in-process executor is the usual case — the budget is ' +
          'recorded and reported rather than enforced, and the page says which of the two it got. A limit ' +
          'that quietly did nothing would be worse than no limit, because you would plan around it.',
      ) +
      prose(
        'What placement costs and what a budget can and cannot promise are in ' +
          '<a href="/guide/where-it-runs">where a render runs</a>.',
      ),
  },
  {
    slug: 'what-the-route-declares',
    part: 'deliver',
    title: 'What the route declares',
    lede: 'Placement, delivery, cache policy and budgets are declared per route — and every one of them is checked against what the compiler inferred.',
    goal:
      'Write a declaration that contradicts what the compiler saw, and read the refusal — then write ' +
      'the one that agrees and see it accepted without changing a line of the fragment.',
    body: () =>
      prose(
        'You have now declared three things without noticing: that a slot streams, where it runs, and what ' +
          'it may spend. A route declaration is the whole list, and its rule is simple — you may declare ' +
          'anything the compiler cannot infer, and nothing it can.',
      ) +
      heading('1 · Declare a cache class it can disprove', 'contradict') +
      diff(
        ["  body: { fragment: 'today', load: … },", "+ cache: { class: 'public', ttl: '5m' },"],
        'app/routes/index.data.ts',
      ) +
      prose(
        'The fragment reads <code>cookie:currency</code>, which you added two steps ago. A public entry ' +
          'for a page that varies per reader would put one person’s prices in another person’s cache, so ' +
          'the build stops:',
      ) +
      terminal('refuse-cache', [
        {
          label: 'weft build',
          lines: [
            '$ npx weft build',
            '  E_PRIVATE_AS_PUBLIC  routes/index.data.ts declares cache.class public',
            '                       fragments/today reads cookie:currency',
            '                       a public policy on a fragment classified private would put one',
            '                       user of the site in another one of their caches',
          ],
        },
      ]) +
      prose(
        'The message names the read that refused you rather than the rule you broke, which is the ' +
          'difference between a refusal you can act on and one you have to go and look up.',
      ) +
      heading('2 · Declare what it cannot see instead', 'agree') +
      sketch(
        'ts',
        `export default defineRoute({
  head: { title: 'Shop' },
  cache: { ttl: '5m' },        // how long — it cannot know your data
  slots: {
    body: { fragment: 'today', load: … },
    feed: { fragment: 'feed', stream: true, run: 'isolate' },
  },
})`,
      ) +
      prose(
        'The class stays derived and the TTL is yours, because how long a value stays true is a fact about ' +
          'your business and not about your code. <a href="/guide/declarations">What a route declares</a> ' +
          'is the full list, each with the reason it is on the declarable side of the line.',
      ),
  },
  {
    slug: 'a-plan-from-measurement',
    part: 'deliver',
    title: 'A plan generated from measurement',
    lede: 'The file tree cannot say what anything costs. Record it, and let the next build plan delivery from the recording.',
    goal:
      'Record what every region on your page actually costs, then rebuild and find that the plan changed ' +
      'without you editing a route — because delivery is a decision about cost.',
    body: () =>
      prose(
        'Everything so far was declared or derived from shape. Neither can answer the one question ' +
          'delivery turns on: what does this region cost <em>here</em>, on this data, on this machine. So ' +
          'the framework measures it and plans from the measurement.',
      ) +
      heading('1 · Record a profile', 'record') +
      sketch(
        'sh',
        `npx weft dev --profile        # exercise the pages you care about
npx weft build --profile .weft/profile.json`,
      ) +
      prose(
        'The profile is a file of timings per region, written by running the thing rather than by ' +
          'estimating it. It is an input to the build, so it is reviewable and it is diffable.',
      ) +
      heading('2 · Read what changed in the plan', 'changed') +
      terminal('why-profile', [
        {
          label: 'weft why',
          lines: [
            '$ weft why /',
            '  wave 1   header (buffered) · today (buffered)',
            '  wave 2   feed (stream) — p95 168 ms, over the in-order threshold',
            '  from     .weft/profile.json · 214 samples',
          ],
        },
      ]) +
      prose(
        'No route changed. The plan did, because the measurement did — and the line that says so names the ' +
          'file and the sample count, so a plan you disagree with is a measurement you can go and look at.',
      ) +
      note(
        'why',
        'Why a guess would have been worse than nothing',
        'A delivery strategy chosen from the shape of the code is a guess that never gets corrected, and ' +
          'the shape of the code is the one thing that does not change when your data does. Measuring is ' +
          'the only version of this that is still right in six months.',
      ) +
      prose(
        '<a href="/guide/measuring">A plan generated from measurement</a> has what is recorded, what the ' +
          'thresholds are, and what happens on a page with no profile at all.',
      ),
  },
  {
    slug: 'making-it-change',
    part: 'change',
    title: 'Making it change: intents and authority',
    lede: 'An intent to write, and a live region to show the result.',
    goal:
      'Write something — the one way this framework allows it — and have the regions that went stale ' +
      'refresh themselves because the intent declared which ones they were.',
    body: () =>
      prose(
        'A render cannot write. So a mutation is an intent, in its own directory, declaring the tags it may ' +
          'invalidate:',
      ) +
      heading('1 · Declare the intent', 'declare-intent') +
      sketch(
        'ts',
        `// app/intents/cart.ts
import { defineIntent } from '@weftjs/core'

export const add = defineIntent<{ sku: string }>({
  name: 'cart.add',
  writes: ['cart'],
  input: (raw) => ({ sku: String((raw as { sku?: unknown }).sku ?? '') }),
  async run(ctx, { sku }) {
    await db.cart.add(ctx.session, sku)
    await ctx.revalidate('cart')
  },
})`,
      ) +
      heading('2 · Name it from a control', 'name-it') +
      prose('Wire it to a control by naming it, not by writing a handler:') +
      sketch(
        'tsx',
        `import { add } from '../intents/cart.ts'

<button onClick={add} data-sku={item.sku}>add</button>`,
      ) +
      prose(
        'With no JavaScript this is a form post, dispatched in phase A, so a real status and a 303 are both ' +
          'available. With the runtime present it goes over the channel, the client stages its guess in an ' +
          'epoch, and the server replaces the guess with the truth in one paint.',
      ) +
      heading('3 · Make the region live', 'live') +
      sketch('ts', `body: { fragment: 'cart', live: true, load: loadCart }`) +
      prose(
        '<code>live</code> is what lets a region be refreshed over the channel rather than by reloading the ' +
          'page. What arrives is the smallest form the client can prove it can apply — usually a delta, which ' +
          'is the changed values and nothing else.',
      ),
  },
  {
    slug: 'live-regions',
    part: 'change',
    title: 'Live regions and the channel',
    lede: 'A region refreshed over a channel, and the smallest honest form is a delta computed once for every client on the same base.',
    goal:
      'Open a channel, name the region a write invalidates, and watch one delta serve every client that ' +
      'is holding the same base — rather than one render each.',
    body: () =>
      prose(
        'The intent you wrote refreshes the cart because it declared that it does. What arrives is a ' +
          'question of form, and the form is negotiated: full markup for a client that has nothing, a ' +
          'patch for one that has an older version, a delta for one holding the exact base this update ' +
          'was computed against.',
      ) +
      heading('1 · Make the region live', 'live') +
      diff(
        [
          "  total: { fragment: 'cart/total', needs: ['items'] },",
          "+ total: { fragment: 'cart/total', needs: ['items'],",
          '+          live: true },',
        ],
        'app/routes/index.data.ts',
      ) +
      prose(
        'One flag, and the region is addressable after the page has painted. The client subscribes on ' +
          'adoption; nothing else about the fragment changes, because a live region is the same sealed ' +
          'template reached a second way.',
      ) +
      heading('2 · Watch the wire', 'wire') +
      terminal('channel', [
        {
          label: 'weft dev',
          lines: [
            '$ npx weft dev --devtools',
            '  channel  open · 3 clients on base 1cc44d9',
            '  update   cart/total → delta 61 B · computed once, sent 3×',
            '  client 4 joined on no base → html 412 B',
          ],
        },
      ]) +
      prose(
        'Three clients, one computation. The delta is a function of two states, so every client holding ' +
          'the same base can be sent the same bytes — which is why the base is named by content address ' +
          'rather than by a client id.',
      ) +
      heading('3 · What a delta is not', 'not-a-diff') +
      prose(
        'It is not a DOM diff. There is no second tree to compare against and nothing to reconcile: the ' +
          'template says where every value sits, so a changed value is a write to a known place. That is ' +
          'the whole reason a thousand clients cost one diff — see ' +
          '<a href="/guide/live-regions">live regions and the channel</a>.',
      ),
  },
  {
    slug: 'signals-and-adoption',
    part: 'change',
    title: 'Signals, and what the client adopts',
    lede: 'Client-owned state in the template, and adoption that binds what is already painted instead of rendering it again.',
    goal:
      'Add a quantity control that updates in place, and read what the client attached to do it — one ' +
      'binding per value that moves, and no component code at all.',
    body: () =>
      prose(
        'Some state never needs the server. A quantity stepper beside each row is the reader’s, until they ' +
          'commit it. That is a signal: a value the template declares, the client owns, and the server ' +
          'renders an initial value for.',
      ) +
      heading('1 · Declare the signal', 'signal') +
      sketch(
        'tsx',
        `// app/fragments/qty.tsx
import { fragment, signal } from '@weftjs/core'

export default fragment(({ sku }: { sku: string }) => {
  const qty = signal(1)
  return (
    <span class="qty">
      <button on:click={() => qty.set(qty() - 1)}>−</button>
      <input value={qty} />
      <button on:click={() => qty.set(qty() + 1)}>+</button>
    </span>
  )
})`,
      ) +
      heading('2 · Read what adoption cost', 'adopt') +
      prose(
        'There is no hydration here, and the word is avoided on purpose: nothing re-renders to find out ' +
          'what is already on the page. The client walks the wiring the compiler emitted and attaches one ' +
          'binding per value that moves.',
      ) +
      stats([
        { value: '3', note: 'bindings attached — two events and one value', lit: true },
        { value: '0', note: 'components executed on the client' },
        { value: '0.047 ms', note: 'to adopt a 50-row region in Chromium' },
      ]) +
      prose(
        'The cost is the number of bindings, not the number of components — which is why a page of mostly ' +
          'static markup with three live values pays for three.',
      ) +
      note(
        'why',
        'Why this is not hydration by another name',
        'Hydration re-runs your components to discover the tree it should have built, then compares. This ' +
          'reads a list the compiler already wrote and calls <code>addEventListener</code>. The word for ' +
          'what replaces hydration is adoption, and it is a different mechanism rather than a faster one.',
      ) +
      prose(
        '<a href="/guide/the-client">Adoption, signals, and what ships</a> has the wiring format and what ' +
          'a signal may and may not be.',
      ),
  },
  {
    slug: 'instant-navigation',
    part: 'change',
    title: 'Instant navigation',
    lede: 'A click that commits a route already fetched, parsed and painting nothing.',
    goal:
      'Turn the shop’s links into navigations that are already finished when they are clicked, and see ' +
      'that the shell never re-renders because it never changed.',
    body: () =>
      prose(
        'A navigation between two pages under the same layout is not a new document. The shell is ' +
          'identical, so the only thing that has to arrive is the part that differs — and it can arrive ' +
          'before the click.',
      ) +
      heading('1 · Nothing to turn on', 'nothing') +
      prose(
        'The client is already there, because the page adopted. A link to a route in this application is ' +
          'staged on intent — hover, focus, or a touch that has not lifted — and committed on click. What ' +
          'you write is a link:',
      ) +
      sketch('tsx', `<a href="/item/{item.sku}">{item.name}</a>`) +
      heading('2 · Watch a click that costs nothing', 'watch') +
      terminal('nav', [
        {
          label: 'weft dev',
          lines: [
            '$ npx weft dev --devtools',
            '  hover /item/oat-milk   staged · 1 region, 612 B',
            '  click /item/oat-milk   committed in 4 ms · shell unchanged, 0 bytes',
            '  paint                  1 region replaced, 0 layout of the document',
          ],
        },
      ]) +
      prose(
        'The shell did not move because the plan knows it did not change: both routes name the same ' +
          'document, so the chain above the slot is the same chain. A staged epoch that is never clicked ' +
          'is discarded, and a click that arrives first is awaited rather than raced.',
      ) +
      note(
        'careful',
        'Staging is not prefetching everything',
        'A staged route is one the reader has already shown intent toward. Fetching every link on a page ' +
          'would spend the reader’s data to make one of twenty links faster, which is a trade nobody asked ' +
          'for — <a href="/guide/navigation">instant navigation</a> has the rules.',
      ),
  },
  {
    slug: 'what-the-page-downloads',
    part: 'change',
    title: 'What the page downloads',
    lede: 'The client runtime has a ceiling per entry, and the honest number is the one that is bigger than all of them.',
    goal:
      'Ask what your shop actually sends to a browser, and find out which of your own decisions put each ' +
      'byte there.',
    body: () =>
      prose(
        'You have added a signal, a live region and instant navigation. Each of those is a client entry, ' +
          'and each entry has a byte ceiling the build enforces. Now look at what the page you built ' +
          'downloads.',
      ) +
      heading('1 · Ask', 'ask') +
      sketch('sh', 'npx weft build\npnpm bench budget') +
      terminal('budget', [
        {
          label: 'bench budget',
          lines: [
            '$ pnpm bench budget',
            '  adopt        2,418 B / 2,560 B   brotli',
            '  channel      1,904 B / 2,048 B   brotli',
            '  navigate     1,336 B / 1,536 B   brotli',
            '  ─────────────────────────────────────────',
            '  this page    5,658 B             all three entries, because you used all three',
          ],
        },
      ]) +
      prose(
        'The last line is the one that matters and it is deliberately the largest: a page that adopts, ' +
          'subscribes and navigates pays for all three, and reporting only the smallest entry would be a ' +
          'number chosen to flatter the framework.',
      ) +
      heading('2 · Spend less by declaring less', 'less') +
      table(
        ['Take away', 'What stops shipping'],
        [
          ['The quantity signal', '<code>adopt</code> — a page with no wiring gets no client at all'],
          ['<code>live: true</code>', '<code>channel</code> — nothing subscribes, so nothing is sent'],
          ['Nothing', 'the shell is markup, and markup has no runtime'],
        ],
      ) +
      prose(
        'Every byte on that list is there because a declaration you made put it there, which means every ' +
          'byte is one you can remove by removing the declaration. ' +
          '<a href="/guide/what-ships">What the page downloads</a> has the ceilings and how they are held.',
      ),
  },
  {
    slug: 'shipping-it',
    part: 'ship',
    title: 'Building, and the tier where a page is a file',
    lede: 'Build, look at what the build says, and deploy the tier below the kernel.',
    goal:
      'Build the application, read which pages became files and why the rest did not, and serve the ' +
      'result from the tier where the kernel is never invoked.',
    body: () =>
      prose('The build is one command, and its report is the thing worth reading:') +
      heading('1 · Build it', 'build') +
      sketch('sh', 'npx weft build') +
      prose(
        'It prints a line per route — slots, markup bytes, stylesheets — then the L0 section: which pages ' +
          'were resolved at build time and written as files, and for every page that was not, the code and ' +
          'the read that refused it. That list is the performance review of your application, and it is ' +
          'generated rather than requested.',
      ) +
      heading('2 · Serve it, and check it', 'serve-it') +
      sketch(
        'sh',
        `npx weft start          # serve the build. No compiler runs
npx weft verify --probe # ask every region what it is serving
npx weft upload --to …  # PUT the build to an object store`,
      ) +
      heading('3 · What the build refused, and why', 'refused') +
      prose(
        'Every page that did not become a file is listed with the read that stopped it. On this shop that ' +
          'is the cart, which reads identity, and the feed, which is somebody else’s. Neither is a fault ' +
          'to fix — the list is the performance review of your application, and it is generated rather ' +
          'than requested.',
      ) +
      prose(
        'Four steps are left, and they are the ones that turn a running application into a deployed one: ' +
          'what to test, what to bind, what may live elsewhere, and what may change under you.',
      ),
  },
  {
    slug: 'testing-what-you-built',
    part: 'ship',
    title: 'Testing what you built',
    lede: 'A fragment is a pure function of its values, so most of what you would mount a browser for is a call.',
    goal:
      'Test a fragment, a plan and an intent without a browser, and see why the interesting assertions ' +
      'are about what the compiler inferred rather than about pixels.',
    body: () =>
      prose(
        'A sealed template rendered with a value set is a function call. That removes the reason most ' +
          'component tests need a DOM at all, and it leaves the assertions that are actually about this ' +
          'framework: what a fragment reads, what its class came out as, and what a route refuses.',
      ) +
      heading('1 · Render a fragment', 'render') +
      sketch(
        'ts',
        `import { render } from '@weftjs/ir'
import { fragmentIR } from '@weftjs/core'

test('a row shows the price it was given', () => {
  const item = fragmentIR('item')
  const html = render(item.entry, { item: { sku: 'oat', name: 'Oat milk', price: 3.9 } })
  assert.match(String(html), /Oat milk/)
})`,
      ) +
      heading('2 · Assert on the plan, not the pixels', 'plan') +
      sketch(
        'ts',
        `test('reading the currency cookie takes the page out of static', async () => {
  const plan = await planFor('/')
  assert.equal(plan.slots.body.class, 'shared')
  assert.deepEqual(plan.slots.body.reads, ['cookie:currency'])
})`,
      ) +
      prose(
        'That test fails the day somebody adds a read, which is exactly the day you want to be told. A ' +
          'snapshot of the markup would have failed too — and for a reason that did not name the cause.',
      ) +
      heading('3 · Test the refusals you rely on', 'refusals') +
      sketch(
        'ts',
        `test('a public class on a private fragment is refused by name', async () => {
  await assert.rejects(() => build({ cache: { class: 'public' } }), /E_PRIVATE_AS_PUBLIC/)
})`,
      ) +
      prose(
        'A refusal you depend on is a behaviour, and a behaviour with no test is a behaviour that leaves ' +
          'quietly. <a href="/guide/testing">Checking your own application</a> has the helpers and what ' +
          'each one is for.',
      ),
  },
  {
    slug: 'ports-and-deployment',
    part: 'ship',
    title: 'Ports, config and deployment',
    lede: 'A port is a capability bound at the edge of the application, and a config file exists to bind them.',
    goal:
      'Bind the store, the clock and the rate limiter your shop has been using implicitly, and deploy the ' +
      'result to somewhere that is not your laptop.',
    body: () =>
      prose(
        'Your shop has been running on defaults: an in-process store, a cookie session, and ' +
          '<code>inline</code> as the only executor. Every one of those is a port — a capability the ' +
          'kernel asks for by name — and <code>weft.config.ts</code> is the one file whose job is to bind ' +
          'them. A first application binds none, which is why you have not needed the file until now.',
      ) +
      heading('1 · Bind them', 'bind') +
      sketch(
        'ts',
        `// weft.config.ts
import { bySession, defineConfig, redisLeases } from '@weftjs/core'

export default defineConfig({
  port: 4173,
  store: redisLeases(process.env.REDIS_URL!),
  limits: { counted: bySession('sid') },
  authority: { grants: { anonymous: ['cart:add'] } },
})`,
      ) +
      prose(
        'Each line answers something the kernel refuses to guess. What a call is counted against is the ' +
          'clearest of them: a deployment behind a CDN counts by address, one where every caller has a ' +
          'subject counts by subject, and nothing in your application knows which of those it is behind. ' +
          'Delete the grant and every add becomes <code>E_CAPABILITY_DENIED</code> with the missing ' +
          'capability named — the framework refuses, and the config is where the answer lives.',
      ) +
      heading('2 · Deploy the tier you built', 'deploy') +
      sketch(
        'sh',
        `npx weft build
npx weft upload --to s3://shop-static   # the L0 pages: files, no kernel
npx weft start                          # the rest, wherever you run Node`,
      ) +
      prose(
        'The pages the build resolved are objects in a bucket and never reach your server. What is left is ' +
          'the part that genuinely varies per request, which on this shop is the cart and the feed.',
      ) +
      note(
        'careful',
        'A store on an edge key-value namespace refuses leases',
        'It refuses outright rather than approximating one. A lease that is not atomic is a stampede guard ' +
          'that does not guard and a replay guard that reports every nonce fresh, and both failures are ' +
          'silent — which is why the port says no instead.',
      ) +
      prose(
        '<a href="/guide/deploying">Ports, config, and the build</a> lists every port, what binds it, and ' +
          'what each adapter can and cannot promise.',
      ),
  },
  {
    slug: 'a-remote-region',
    part: 'ship',
    title: 'A region that lives somewhere else',
    lede: 'One region of your page rendered by another deployment, over the protocol the page already speaks.',
    goal:
      'Move the recommendations feed to a service that owns it, and find that nothing about the page ' +
      'changes except where one hole is filled from.',
    body: () =>
      prose(
        'The feed belongs to another team. That is an organisational fact, and it usually becomes an ' +
          'architectural one — an iframe, a build-time package, a second bundle. Here it is a slot whose ' +
          'fill arrives from somewhere else, because a slot was always a boundary.',
      ) +
      heading('1 · Point the slot elsewhere', 'point') +
      diff(
        [
          "  feed: { fragment: 'feed', stream: true,",
          "-         run: 'isolate' },",
          "+         from: 'https://recs.internal/regions/feed' },",
        ],
        'app/routes/index.data.ts',
      ) +
      prose(
        'No new protocol. The remote answers with the same wire forms this page already negotiates — full ' +
          'markup, a patch or a delta — so the client that adopts the region does not know or care which ' +
          'deployment rendered it.',
      ) +
      heading('2 · What crosses the boundary', 'boundary') +
      table(
        ['Crosses', 'Does not'],
        [
          ['The values the slot declared it needs', 'Your session, unless the slot declared it needs it'],
          ['The region’s markup, patch or delta', 'Your database, your ports, your intents'],
          ['A budget, and what happens if it is missed', 'Any authority the region did not ask for'],
        ],
      ) +
      prose(
        'A region that writes into a sibling’s slot is <code>E_REGION_ESCAPE</code>, and that rule does ' +
          'not relax because the region is remote — it is the property that makes this safe rather than ' +
          'convenient. See <a href="/guide/composition">a region that lives somewhere else</a>.',
      ),
  },
  {
    slug: 'every-surface',
    part: 'ship',
    title: 'Every surface, and what may change',
    lede: 'The same declarations answering a watch, a terminal and a feed reader — and the rules for changing any of it without breaking a client.',
    goal:
      'Serve the shop to something that is not a browser, then read what this framework promises about ' +
      'the formats you have been relying on.',
    body: () =>
      prose(
        'A region is a rendered fragment addressed by name. Nothing in that sentence says HTML, and ' +
          'nothing in your route said it either — the form was negotiated per request all along.',
      ) +
      heading('1 · Ask for another surface', 'surface') +
      terminal('surfaces', [
        {
          label: 'curl',
          lines: [
            '$ curl -H "Accept: application/json" localhost:4173/            # the value set',
            '$ curl -H "Accept: text/plain" localhost:4173/                  # for a terminal',
            '$ curl -H "Accept: application/warp" localhost:4173/            # frames, for a client',
          ],
        },
      ]) +
      prose(
        'Same route, same fragments, same plan. A surface that cannot take one of the forms is served the ' +
          'one it can, which is the negotiation this framework is named for.',
      ) +
      heading('2 · What may change under you', 'versions') +
      table(
        ['Carries a version', 'What that buys'],
        [
          [
            'The template IR',
            'A client holding an old template is sent markup rather than a delta it cannot apply.',
          ],
          ['The warp frames', 'A frame a client does not understand is skipped, not guessed at.'],
          [
            'Every sealed template',
            'A content address, so "the same template" is a fact rather than a claim.',
          ],
        ],
      ) +
      prose(
        'Those are the three numbers in the pill at the top of this page, and they are stamped by the ' +
          'build rather than typed. <a href="/guide/devices">Every surface at once</a> and ' +
          '<a href="/guide/versioning">versions, and what may change</a> are where this stops being a ' +
          'tutorial and starts being a contract.',
      ),
  },
]

export const STEP_BY_SLUG: Record<string, Step> = Object.fromEntries(STEPS.map((step) => [step.slug, step]))

/**
 * `Part two · Step 6 of 19`, counted rather than written.
 *
 * No step's title carries its own number and none should: a title is what the step is about and a
 * number is where it currently sits. Those were the same thing while there were six of them, and
 * stopped being the same thing the moment thirteen were inserted between them. Everything that
 * shows a number — this line, the index cards, the rail — counts it from the position instead.
 *
 * The part is in front of it because a position needs somewhere to be a position in: `6 of 19` says
 * how far and the part says where.
 */
export function stepKicker(slug: string): string {
  const at = STEPS.findIndex((step) => step.slug === slug)
  if (at < 0) return ''
  const part = PART_BY_ID[STEPS[at]?.part ?? '']
  return `${part ? `${part.ordinal} · ` : ''}Step ${at + 1} of ${STEPS.length}`
}

/**
 * What a step actually has you run, and what it has you hit.
 *
 * Read out of the step's own markup rather than listed beside it: a step that gains a command gains
 * a line here, and a step whose command is renamed cannot go on advertising the old one. The codes
 * are the same bargain — a step that shows a refusal is a step whose card should say which one,
 * because that is what somebody scanning for the answer to an error is scanning for.
 */
export function stepMentions(slug: string): string[] {
  const step = STEP_BY_SLUG[slug]
  if (!step) return []
  const markup = step.body()
  const text = markup.replace(/<[^>]+>/g, ' ')
  const commands = [...text.matchAll(/\bweft ([a-z]+)(?: (\/[a-z-]*))?/g)].map(
    (match) => `weft ${match[1]}${match[2] ? ` ${match[2]}` : ''}`,
  )
  const codes = [...text.matchAll(/\bE_[A-Z0-9_]+/g)].map((match) => match[0])
  return [...new Set([...commands, ...codes])].slice(0, 3)
}

/**
 * How long a step takes, in whole minutes, from the step itself.
 *
 * The design puts a time under each step's progress count, and a time somebody typed is a time that
 * is wrong the first time the step grows. So it is counted from the step.
 *
 * Not reading time — this is a tutorial, and the reader is typing and running things. Prose at 200
 * words a minute, plus three minutes for every block they have to type and watch the result of,
 * which is where a tutorial step's time actually goes. On the step the design costed, that comes
 * out at the eight minutes the design says.
 */
const READING = 200
const PER_BLOCK = 3

export function stepMinutes(slug: string): number {
  const step = STEP_BY_SLUG[slug]
  if (!step) return 0
  const markup = step.body()
  const words = markup
    .replace(/<[^>]+>/g, ' ')
    .split(/\s+/)
    .filter(Boolean).length
  const blocks = (markup.match(/<pre/g) ?? []).length
  return Math.max(2, Math.ceil(words / READING + blocks * PER_BLOCK))
}

/** `about eight minutes`, because a numeral there reads as a promise and a word reads as an estimate. */
const SPELLED = [
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
]

export function stepTime(slug: string): string {
  const minutes = stepMinutes(slug)
  return `about ${SPELLED[minutes] ?? minutes} minutes`
}

/**
 * What the reader's application looks like at the end of each step.
 *
 * The design puts this in the rail, and it earns its place: a tutorial adds a file at a time and by
 * step four the reader has six of them, with no single view of what they now have. The files a step
 * *touched* are marked, so the rail also answers "what did I just change".
 *
 * Cumulative by construction — each step names only what it adds, and the tree is the union of
 * every step up to and including this one. A step cannot forget to list a file it added earlier.
 */
const ADDS: Record<string, readonly string[]> = {
  'a-page': ['app/', 'app/routes/', 'app/routes/index.tsx'],
  'the-document': ['app/layout.tsx'],
  'fragments-and-lists': ['app/fragments/', 'app/fragments/item.tsx', 'app/fragments/price.tsx'],
  'scoped-styles': ['app/fragments/item.scoped.css'],
  'a-loader': ['app/routes/index.data.ts'],
  'a-slow-region': ['app/fragments/feed.tsx', 'app/fragments/feed/', 'app/fragments/feed/skeleton.tsx'],
  'making-it-change': ['app/intents/', 'app/intents/cart.ts'],
  'live-regions': ['app/fragments/cart/', 'app/fragments/cart/total.tsx'],
  'signals-and-adoption': ['app/fragments/qty.tsx'],
  'testing-what-you-built': ['test/', 'test/shop.test.ts'],
  'ports-and-deployment': ['weft.config.ts'],
}

export interface TreeRow {
  path: string
  depth: number
  name: string
  /** Added by the step being read, rather than by one before it. */
  fresh: boolean
}

export function appSoFar(slug: string): TreeRow[] {
  const upTo = STEPS.findIndex((step) => step.slug === slug)
  if (upTo < 0) return []
  const seen: string[] = []
  for (const step of STEPS.slice(0, upTo + 1)) {
    for (const path of ADDS[step.slug] ?? []) if (!seen.includes(path)) seen.push(path)
  }
  const fresh = new Set(ADDS[slug] ?? [])
  return seen.toSorted().map((path) => {
    const parts = path.replace(/\/$/, '').split('/')
    return {
      path,
      depth: parts.length - 1,
      name: path.endsWith('/') ? `${parts.at(-1)}/` : (parts.at(-1) ?? path),
      fresh: fresh.has(path),
    }
  })
}

/**
 * The tutorial's front page: what it costs, then the parts, then the steps in each.
 *
 * Every number on it is counted from the steps — the count, the minutes, the files the reader ends
 * with — because a tutorial index is exactly the page where an estimate somebody typed goes stale
 * first. A part is a row: what it is for on the left, and the steps in it on the right, so the
 * shape of the whole tutorial is one screen rather than a list of six titles.
 */
export function tutorialIndexBody(): string {
  const minutes = STEPS.reduce((sum, step) => sum + stepMinutes(step.slug), 0)
  const last = STEPS.at(-1)
  const files = last ? appSoFar(last.slug).filter((row) => !row.path.endsWith('/')).length : 0

  return (
    stats([
      { value: String(STEPS.length), note: `steps, in ${PARTS.length} parts` },
      { value: clock(minutes), note: 'end to end, counted from the steps themselves' },
      { value: String(files), note: 'files in the application by the last step' },
      { value: '1', note: 'application, carried the whole way', lit: true },
    ]) +
    // The band's rule spans the column while its sentence keeps a readable measure, which is two
    // widths and therefore two elements.
    `<div class="tutorial-band"><p class="hint">You need Node 22 or later and nothing else. There is
     no scaffolding step you cannot read, and every step says what changed, what the framework then
     knew, and which command shows it.</p></div>` +
    PARTS.map((part) => {
      const steps = STEPS.filter((step) => step.part === part.id)
      if (!steps.length) return ''
      const takes = steps.reduce((sum, step) => sum + stepMinutes(step.slug), 0)
      return `<section class="part" id="${escapeHtml(part.id)}">
        <div class="part-of">
          <p class="eyebrow">${escapeHtml(part.ordinal)}</p>
          <h2><a class="anchor" href="#${escapeHtml(part.id)}">${escapeHtml(part.label)}</a></h2>
          <p>${escapeHtml(part.blurb)}</p>
          <p class="hint">${clock(takes)}</p>
        </div>
        <div class="part-steps">${steps.map(stepCard).join('')}</div>
      </section>`
    }).join('') +
    // The outline column's, until this page stopped having one. It is the sentence the tutorial
    // exists to teach, so it moved into the page rather than going with the column.
    note(
      'why',
      'The habit worth learning',
      'After every step, run <code>weft why &lt;route&gt;</code>. The plan is generated from what you ' +
        'wrote, and reading it is how you find out that a declaration you did not make was decided for ' +
        'you — and which read decided it.',
    )
  )
}

/** One step, as the index shows it: where it is, what it does, and what it has you run. */
function stepCard(step: Step): string {
  const at = STEPS.findIndex((other) => other.slug === step.slug) + 1
  const mentions = stepMentions(step.slug)
  return `<a class="step-card" href="/tutorial/${escapeHtml(step.slug)}">
    <div class="step-card-head">
      <span class="step-num">${String(at).padStart(2, '0')}</span>
      <span class="step-title">${escapeHtml(step.title)}</span>
      <span class="step-mins">${stepMinutes(step.slug)} min</span>
    </div>
    <p>${escapeHtml(step.lede)}</p>
    ${mentions.length ? `<p class="step-runs">${mentions.map(escapeHtml).join(' · ')}</p>` : ''}
  </a>`
}

/** `2 h 43` where it runs past an hour, and `43 min` where it does not. */
function clock(minutes: number): string {
  if (minutes < 60) return `${minutes} min`
  return `${Math.floor(minutes / 60)} h ${String(minutes % 60).padStart(2, '0')}`
}

export function stepBody(slug: string): string {
  const step = STEP_BY_SLUG[slug]
  if (!step)
    return `<div class="card"><h3>No such step</h3><p><a href="/tutorial">Start at the beginning</a>.</p></div>`
  const index = STEPS.findIndex((s) => s.slug === slug)
  const previous = index > 0 ? STEPS[index - 1] : undefined
  const next = index < STEPS.length - 1 ? STEPS[index + 1] : undefined
  return (
    `<div class="goal"><p class="goal-kicker">Goal</p><p>${escapeHtml(step.goal)}</p></div>` +
    step.body() +
    `<nav class="sequence">${[
      previous ? `<a class="prev" href="/tutorial/${previous.slug}">← ${escapeHtml(previous.title)}</a>` : '',
      next ? `<a class="next" href="/tutorial/${next.slug}">${escapeHtml(next.title)} →</a>` : '',
    ]
      .filter(Boolean)
      .join('')}</nav>`
  )
}
