import { escapeHtml, heading, note, prose, sketch, table } from './markup.ts'

/**
 * One page, built from nothing, one step at a time.
 *
 * The tutorial's job is different from the guide's: the guide explains a mechanism, and this shows
 * what a mechanism costs by having you add it. Every step says what changed, what the framework then
 * knew, and what command shows it — because "run `weft why /` and look at the plan" is the habit
 * worth teaching, and no amount of prose replaces it.
 */
export interface Step {
  slug: string
  title: string
  lede: string
  body: () => string
}

export const STEPS: readonly Step[] = [
  {
    slug: 'a-page',
    title: '1 — A page',
    lede: 'One file is an application. Nothing is configured and nothing is generated by hand.',
    body: () =>
      prose(
        'Start with a folder. There is no template to instantiate, no config to write, and nothing to ' +
          'register — a route is a file, and this one is the only file you need.',
      ) +
      sketch(
        'sh',
        `mkdir shop && cd shop
npm init -y && npm i weft
mkdir -p app/routes`,
      ) +
      sketch(
        'tsx',
        `// app/routes/index.tsx
import { fragment } from 'weft'

export default fragment(() => (
  <section>
    <h2>Today</h2>
    <p>Nothing yet.</p>
  </section>
))`,
      ) +
      prose('Then:') +
      sketch('sh', 'npx weft dev') +
      heading('What the framework now knows', 'knows') +
      prose(
        'There is no <code>app/layout.tsx</code>, so the page is wrapped in the framework’s own document. ' +
          'Ask what the plan is:',
      ) +
      sketch('sh', 'npx weft routes\nnpx weft why /') +
      prose(
        'One route, one slot named <code>body</code>, delivery <code>buffered</code>. Nothing streams because ' +
          'nothing asked to, and nothing is keyed because the fragment reads nothing — which means this page ' +
          'is already in the tier where a document is a file. <code>npx weft build</code> writes it as one.',
      ),
  },
  {
    slug: 'the-document',
    title: '2 — The document',
    lede: 'Take over the shell, and discover that its holes are a contract.',
    body: () =>
      prose(
        'The framework’s document is a placeholder. Replacing it is adding one file, and the moment you do, ' +
          'its <code>&lt;slot&gt;</code> holes become the boundaries every route has to fill.',
      ) +
      sketch(
        'tsx',
        `// app/layout.tsx
import { fragment, raw } from 'weft'

interface Props {
  title: string
  css: string
  runtime: string
  body: string
  aside: string
}

export default fragment(({ title, css, runtime, body, aside }: Props) => (
  <>
    {raw('<!doctype html>')}
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>{title}</title>
        <link rel="stylesheet" href={css} />
        <script type="module" src={runtime} />
      </head>
      <body>
        <main><slot name="body">{body}</slot></main>
        <aside><slot name="aside">{aside}</slot></aside>
      </body>
    </html>
  </>
))`,
      ) +
      note(
        'careful',
        'The build now fails, and that is the feature',
        'Two holes and one route that fills one of them: <code>E_SHELL_HOLE_UNFILLED</code> names ' +
          '<code>aside</code>. A hole nothing fills would otherwise be an empty box in production that ' +
          'nobody noticed, so it is a build error instead.',
      ) +
      prose('Fill it from the route’s declaration:') +
      sketch(
        'ts',
        `// app/routes/index.data.ts
import { defineRoute } from 'weft'

export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      prose(
        'Note what is <em>not</em> here. <code>body</code> is not declared: the route’s own ' +
          '<code>.tsx</code> fills it, which is the one convention the hole names rely on. ' +
          '<code>title</code>, <code>css</code> and <code>runtime</code> are not declared either — the ' +
          'framework supplies six values every document may read, and a hole outside that set has to come ' +
          'from <code>layoutValues</code> or the build says so.',
      ),
  },
  {
    slug: 'a-loader',
    title: '3 — Data, and the first cache key',
    lede: 'Load something. Watch the cache class change without declaring one.',
    body: () =>
      prose(
        'A slot’s <code>load</code> is where data comes from. Its result is the value set the fragment ' +
          'renders with — there is no separate props step and no context to thread.',
      ) +
      sketch(
        'tsx',
        `// app/fragments/today.tsx
import { fragment } from 'weft'

interface Item { sku: string; name: string; price: number }

export default fragment(({ items }: { items: Item[] }) => (
  <ul>
    {items.map((item) => (
      <li><code>{item.sku}</code> {item.name} — {item.price}</li>
    ))}
  </ul>
))`,
      ) +
      sketch(
        'ts',
        `// app/routes/index.data.ts
export default defineRoute({
  head: { title: 'Shop' },
  slots: {
    body: { fragment: 'today', load: async () => ({ items: await db.today() }) },
    aside: { html: '<p>Open 9–6.</p>' },
  },
})`,
      ) +
      heading('Now make it vary', 'vary') +
      prose(
        'Read the request inside the fragment and the page changes class. One line, and nothing declares ' +
          'the consequence:',
      ) +
      sketch(
        'tsx',
        `export default fragment(({ items }: { items: Item[] }, ctx) => {
  const currency = ctx.cookie('currency') ?? 'USD'
  return <ul data-currency={currency}>…</ul>
})`,
      ) +
      table(
        ['Before', 'After'],
        [
          [
            'reads nothing → <code>static</code>, resolvable at build time',
            'reads <code>cookie:currency</code> → <code>shared</code>, keyed by value, <code>Vary: Cookie</code>',
          ],
        ],
      ) +
      prose(
        '<code>npx weft build</code> now refuses to write this page as a file, and says which read stopped ' +
          'it. That refusal is the whole design in one line: the cheapest tier is not something you opt ' +
          'into, it is something a read takes you out of.',
      ),
  },
  {
    slug: 'a-slow-region',
    title: '4 — A slow region, and the first byte',
    lede: 'Add something slow and watch the shell stop waiting for it.',
    body: () =>
      prose(
        'One region on the page is slow — a recommendation query, say. Declare that it streams, and the ' +
          'document stops being downstream of it.',
      ) +
      sketch(
        'ts',
        `slots: {
  body: { fragment: 'today', load: today },
  aside: {
    fragment: 'recs',
    stream: { prio: 1 },
    placeholder: '<p class="skeleton"></p>',
    load: async () => ({ items: await slowRecommendations() }),
  },
}`,
      ) +
      prose(
        'The plan’s delivery order was <code>in-order</code> and is now <code>out-of-order</code>, because ' +
          'a slot asked to stream. That is derived, not declared: a page whose regions are uniformly fast ' +
          'never puts the fill script on the wire at all.',
      ) +
      sketch('sh', 'npx weft why / | grep -A2 delivery') +
      heading('What a placeholder is for', 'placeholder') +
      prose(
        'It is what arrives if the region degrades — over budget, or a loader that threw. Honest, cheap and ' +
          'visibly incomplete, which is the only useful behaviour: a region that failed and rendered ' +
          'something plausible is worse than one that failed and said so.',
      ) +
      note(
        'why',
        'Why the first byte does not move',
        'The shell’s bytes do not depend on the slow loader — that is what makes it a hole rather than part ' +
          'of the document. So the header, the nav and everything before the slot are on the wire while the ' +
          'query is still running, and the reader sees a page rather than a spinner.',
      ),
  },
  {
    slug: 'making-it-change',
    title: '5 — Making it change',
    lede: 'An intent to write, and a live region to show the result.',
    body: () =>
      prose(
        'A render cannot write. So a mutation is an intent, in its own directory, declaring the tags it may ' +
          'invalidate:',
      ) +
      sketch(
        'ts',
        `// app/intents/cart.ts
import { intent } from 'weft'

export const add = intent({
  writes: ['cart'],
  params: { sku: 'string' },
  async run(ctx, { sku }) {
    await db.cart.add(ctx.session, sku)
    ctx.revalidate('cart')
  },
})`,
      ) +
      prose('Wire it to a control by naming it, not by writing a handler:') +
      sketch(
        'tsx',
        `import { add } from '../intents/cart.ts'

<button onClick={add} data-sku={item.sku}>add</button>`,
      ) +
      prose(
        'With no JavaScript this is a form post, dispatched in phase A, so a real status and a 303 are both ' +
          'available. With the runtime present it goes over the channel, the client stages its guess in an ' +
          'epoch, and the server replaces the guess with the truth in one paint.',
      ) +
      heading('And make the region live', 'live') +
      sketch('ts', `body: { fragment: 'cart', live: true, load: loadCart }`) +
      prose(
        '<code>live</code> is what lets a region be refreshed over the channel rather than by reloading the ' +
          'page. What arrives is the smallest form the client can prove it can apply — usually a delta, which ' +
          'is the changed values and nothing else.',
      ),
  },
  {
    slug: 'shipping-it',
    title: '6 — Shipping it',
    lede: 'Build, look at what the build says, and deploy the tier below the kernel.',
    body: () =>
      prose('The build is one command, and its report is the thing worth reading:') +
      sketch('sh', 'npx weft build') +
      prose(
        'It prints a line per route — slots, markup bytes, stylesheets — then the L0 section: which pages ' +
          'were resolved at build time and written as files, and for every page that was not, the code and ' +
          'the read that refused it. That list is the performance review of your application, and it is ' +
          'generated rather than requested.',
      ) +
      sketch(
        'sh',
        `npx weft start          # serve the build. No compiler runs
npx weft verify --probe # ask every region what it is serving
npx weft upload --to …  # PUT the build to an object store`,
      ) +
      heading('What to do next', 'next') +
      prose(
        'Two things pay for themselves immediately. <code>weft dev --profile</code> records what every ' +
          'render costs and lets the next build plan delivery from measurement instead of a guess. And ' +
          '<code>pnpm inspect</code> opens the inspector — a page per mechanism, each with a control — which ' +
          'is the fastest way to build an intuition for what any of this costs.',
      ),
  },
]

export const STEP_BY_SLUG: Record<string, Step> = Object.fromEntries(STEPS.map((step) => [step.slug, step]))

export function stepContents(current?: string): string {
  return `<h2 class="hint">Steps</h2><ol class="contents">${STEPS.map(
    (step) =>
      `<li>${
        step.slug === current
          ? `<strong>${escapeHtml(step.title)}</strong>`
          : `<a href="/tutorial/${step.slug}">${escapeHtml(step.title)}</a>`
      }</li>`,
  ).join('')}</ol>`
}

export function stepBody(slug: string): string {
  const step = STEP_BY_SLUG[slug]
  if (!step)
    return `<div class="card"><h3>No such step</h3><p><a href="/tutorial">Start at the beginning</a>.</p></div>`
  const index = STEPS.findIndex((s) => s.slug === slug)
  const previous = index > 0 ? STEPS[index - 1] : undefined
  const next = index < STEPS.length - 1 ? STEPS[index + 1] : undefined
  return (
    step.body() +
    `<nav class="sequence">${[
      previous ? `<a class="prev" href="/tutorial/${previous.slug}">← ${escapeHtml(previous.title)}</a>` : '',
      next ? `<a class="next" href="/tutorial/${next.slug}">${escapeHtml(next.title)} →</a>` : '',
    ]
      .filter(Boolean)
      .join('')}</nav>`
  )
}
